# importing the module 'random' to be able to generate random numbers
import random


# A function which validates the input entered by the user such that the user is informed
# and requested to re-enter a value if characters are inputted instead of numbers.
# This function has no parameters passed to it but returns 3 integer values
def user_input():

    # A counter variable is initialised to 1
    i = 1

    # A while loop which runs indefinitely
    while True:

        # Section of code which handles exceptions
        try:

            # This section of code runs again each time until correct input is entered by the
            # user and accepted by the program thus increasing the value of i to 2
            if i is 1:
                x = int(input("\nEnter the max amount of integers in the list: "))
                i += 1
                continue

            # This section of code runs again each time until correct input is entered by the
            # user and accepted by the program thus increasing the value of i to 3
            elif i is 2:
                y = int(input("\nEnter the min value an integer present in the list can have: "))
                i += 1
                continue

            # This section of code runs again each time until correct input is entered by the
            # user and accepted by the program thus increasing the value of i to 4
            elif i is 3:
                z = int(input("\nEnter the max value an integer present in the list can have: "))
                i += 1
                continue

            # The user is informed in this part that all inputs were correct and these
            # values are then returned back
            elif i is 4:
                print("All inputs were successfully stored and the list is shown below:\n")
                return x, y, z

        # Informs the user if anything other than an integer is inputted
        except ValueError:
            print("Invalid input!")


# A function which based on the 3 parameters passed (size of list, min value in list and
# max value in list) which were previously entered by the user, generates a list of randoms
# These numbers are then returned
def generate_list(x, y, z):

    # An empty list to store the random numbers
    numbers = []

    # A for loop which loops through each individual empty element in the array
    # and populates it
    for i in range(x):

        # Generates a random number from y-z each time and stores it in the array
        numbers.append(random.randint(y, z))

    # The numbers are then returned
    return numbers


# A recursive function which finds the largest number in the list passed as a
# first parameter and the size of it as the second
# The max number found is returned back
def find_max(numbers, x):

    # if there is only 1 number in the list then just that number is returned
    if x == 1:
        return numbers[0]

    # else the max number of all the numbers in the list is determined by
    # recursively calling the function each time
    else:
        return max(numbers[x-1], find_max(numbers, x-1))


print("Welcome to this program which finds the largest number from a list of randomly generated integers")

# The inputs entered by the user for the size, min and max values of the list
# are validated in the user_input() function. These are then
# returned and stored in the variables a, b & c respectively
a, b, c = user_input()

# The function generate_list() is then called and the placeholders a, b, c are
# passed as parameters to this function
# The list generated by this function is returned and stored in the sequence
# placeholder
sequence = generate_list(a, b, c)

# This sequence is then printed out
print(sequence)

# The find_max() function is called and the max value found is returned
print("\nThe max value found is:", find_max(sequence, a))
